spring:
  application:
    name: RabbitMqDemo

  # RabbitMQ configuration
  rabbitmq:
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 2.0
        max-attempts: 3
    host: localhost
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123456
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: true
      direct:
        acknowledge-mode: auto
    publisher-confirm-type: correlated
    publisher-returns: true