spring:
  application:
    name: RabbitMqDemo

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: hmall
    password: 123456
    listener:
      simple:
        prefetch: 1